### ISSUE TITLE
请问一下 怎么处理这个报错获取imel

### ISSUE THREAD

**Issue by yingzhong27** [TencentCloud/TPNS-Flutter-Plugin#32]
```
W/JavaCalls( 9822): Meet exception when call Method 'getImei' in android.telephony.TelephonyManager@8d67c4c
W/JavaCalls( 9822): java.lang.reflect.InvocationTargetException
W/JavaCalls( 9822): 	at java.lang.reflect.Method.invoke(Native Method)
W/JavaCalls( 9822): 	at com.xiaomi.push.ac.b(Unknown Source:16)
W/JavaCalls( 9822): 	at com.xiaomi.push.ac.a(Unknown Source:0)
W/JavaCalls( 9822): 	at com.xiaomi.push.gw.g(Unknown Source:94)
W/JavaCalls( 9822): 	at com.xiaomi.push.gw.f(Unknown Source:4)
W/JavaCalls( 9822): 	at com.xiaomi.mipush.sdk.MiPushClient$3.run(Unknown Source:76)
W/JavaCalls( 9822): 	at java.lang.Thread.run(Thread.java:923)
W/JavaCalls( 9822): Caused by: java.lang.SecurityException: getImeiForSlot: The user 10902 does not meet the requirements to access device identifiers.
W/JavaCalls( 9822): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2376)
W/JavaCalls( 9822): 	at android.os.Parcel.createException(Parcel.java:2360)
W/JavaCalls( 9822): 	at android.os.Parcel.readException(Parcel.java:2343)
W/JavaCalls( 9822): 	at android.os.Parcel.readException(Parcel.java:2285)
W/JavaCalls( 9822): 	at com.android.internal.telephony.ITelephony$Stub$Proxy.getImeiForSlot(ITelephony.java:11511)
W/JavaCalls( 9822): 	at android.telephony.TelephonyManager.getImei(TelephonyManager.java:2059)
W/JavaCalls( 9822): 	at android.telephony.TelephonyManager.getImei(TelephonyManager.java:2014)
W/JavaCalls( 9822): 	... 7 more
2
V/xiaomi  ( 9822): [Thread:35388] get region from system, region = CN
W/JavaCalls( 9822): Meet exception when call Method 'getImei' in android.telephony.TelephonyManager@8d67c4c
W/JavaCalls( 9822): java.lang.reflect.InvocationTargetException
W/JavaCalls( 9822): 	at java.lang.reflect.Method.invoke(Native Method)
W/JavaCalls( 9822): 	at com.xiaomi.push.ac.b(Unknown Source:16)
W/JavaCalls( 9822): 	at com.xiaomi.push.ac.a(Unknown Source:0)
W/JavaCalls( 9822): 	at com.xiaomi.push.gw.g(Unknown Source:94)
W/JavaCalls( 9822): 	at com.xiaomi.push.gw.i(Unknown Source:34)
W/JavaCalls( 9822): 	at com.xiaomi.push.gw.j(Unknown Source:0)
W/JavaCalls( 9822): 	at com.xiaomi.push.gw.h(Unknown Source:4)
W/JavaCalls( 9822): 	at com.xiaomi.mipush.sdk.MiPushClient$3.run(Unknown Source:109)
W/JavaCalls( 9822): 	at java.lang.Thread.run(Thread.java:923)
W/JavaCalls( 9822): Caused by: java.lang.SecurityException: getImeiForSlot: The user 10902 does not meet the requirements to access device identifiers.
W/JavaCalls( 9822): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2376)
W/JavaCalls( 9822): 	at android.os.Parcel.createException(Parcel.java:2360)
W/JavaCalls( 9822): 	at android.os.Parcel.readException(Parcel.java:2343)
W/JavaCalls( 9822): 	at android.os.Parcel.readException(Parcel.java:2285)
W/JavaCalls( 9822): 	at com.android.internal.telephony.ITelephony$Stub$Proxy.getImeiForSlot(ITelephony.java:11511)
W/JavaCalls( 9822): 	at android.telephony.TelephonyManager.getImei(TelephonyManager.java:2059)
W/JavaCalls( 9822): 	at android.telephony.TelephonyManager.getImei(TelephonyManager.java:2014)
W/JavaCalls( 9822): 	... 9 more
V/xiaomi  ( 9822): [Thread:35388] create id manager is: com.xiaomi.push.w@2959867
```

**Comment by yingzhong27** [comment]
目前插件版本为V1.1.6
flutter版本为 2.8.1

**Comment by stevenxiaowen** [comment]
您好，所述堆栈日志来自接入的小米离线推送SDK，实际不影响小米设备离线推送业务运行，可直接忽视。
