### ISSUE TITLE
您好 请问可以更新一下tpns的sdk吗？

### ISSUE THREAD

**Issue by yingzhong27** [TencentCloud/TPNS-Flutter-Plugin#36]
TPNS SDK 1.3.3.0 起支持荣耀推送通道接入。荣耀通道是由荣耀官方提供的系统级推送通道。在荣耀手机上，推送消息能够通过荣耀的系统通道抵达终端，并且无需打开应用，即可收到推送，

目前我看插件最新的是
implementation 'com.tencent.tpns:tpns:1.3.2.0-release

目前我这边反馈了一个问题 荣耀的手机 没有角标  

手机是 麦芒11 5G

**Comment by yingzhong27** [comment]
```
I/| XgpushpPlugin | Flutter | Android | (17404): setBadgeNum
I/| XgpushpPlugin | Flutter | Android | (17404): 调用信鸽SDK-->setBadgeNum()-----badgeNum=2
W/System.err(17404): java.lang.NumberFormatException: s == null
W/System.err(17404): 	at java.lang.Integer.parseInt(Integer.java:577)
W/System.err(17404): 	at java.lang.Integer.parseInt(Integer.java:650)
W/System.err(17404): 	at com.loc.et.a(Unknown Source:57)
W/System.err(17404): 	at com.loc.et.a(Unknown Source:96)
W/System.err(17404): 	at com.loc.et$b.onCellInfoChanged(Unknown Source:48)
W/System.err(17404): 	at android.telephony.PhoneStateListener$IPhoneStateListenerStub.lambda$onCellInfoChanged$20(PhoneStateListener.java:1220)
W/System.err(17404): 	at android.telephony.-$$Lambda$PhoneStateListener$IPhoneStateListenerStub$Q2A8FgYlU8_D6PD78tThGut_rTc.run(Unknown Source:4)
W/System.err(17404): 	at android.os.Handler.handleCallback(Handler.java:955)
W/System.err(17404): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(17404): 	at android.os.Looper.loop(Looper.java:228)
W/System.err(17404): 	at android.os.HandlerThread.run(HandlerThread.java:67)
W/System.err(17404): 	at com.loc.e$b.run(Unknown Source:0)
```
还是华为的麦芒11 5g 角标设置不了 无法清除 也无法设置 这是控制台的错误  不知道是否有关系 测试了别的华为手机 正常显示

**Comment by rockzuo-104** [comment]
您好，请升级到V1.1.7版本，谢谢！
