### ISSUE TITLE
example运行报错

### ISSUE THREAD

**Issue by eaaomk** [TencentCloud/TPNS-Flutter-Plugin#8]
java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.xg.tpns_flutter_plugin_example-1/base.apk"],nativeLibraryDirectories=[/data/app/com.xg.tpns_flutter_plugin_example-1/lib/arm, /data/app/com.xg.tpns_flutter_plugin_example-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
E/FlutterLoader( 2887): 	at java.util.concurrent.FutureTask.report(FutureTask.java:94)
E/FlutterLoader( 2887): 	at java.util.concurrent.FutureTask.get(FutureTask.java:164)
E/FlutterLoader( 2887): 	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:200)
E/FlutterLoader( 2887): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:317)
E/FlutterLoader( 2887): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:204)
E/FlutterLoader( 2887): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:244)
E/FlutterLoader( 2887): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:155)
E/FlutterLoader( 2887): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:409)
E/FlutterLoader( 2887): 	at android.app.Activity.performCreate(Activity.java:6739)
E/FlutterLoader( 2887): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
E/FlutterLoader( 2887): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
E/FlutterLoader( 2887): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
E/FlutterLoader( 2887): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
E/FlutterLoader( 2887): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
E/FlutterLoader( 2887): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/FlutterLoader( 2887): 	at android.os.Looper.loop(Looper.java:154)
E/FlutterLoader( 2887): 	at android.app.ActivityThread.main(ActivityThread.java:6121)
E/FlutterLoader( 2887): 	at java.lang.reflect.Method.invoke(Native Method)
E/FlutterLoader( 2887): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
E/FlutterLoader( 2887): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
E/FlutterLoader( 2887): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.xg.tpns_flutter_plugin_example-1/base.apk"],

**Comment by eaaomk** [comment]
是flutter 版本的问题吗？clone下来运行报错。
